import React from 'react'
import { Container, Row, Col, Image } from 'react-bootstrap'

import TriathlonIndex from "./TriathlonIndex"

export default function TriAthleteNutrition() {

    return (
        <Container>
            <Row>
                <TriathlonIndex />
                <Col>
                    <h1>Nutrition For Athletes</h1>
                    <p>The trouble with most of our meals is that we get a lot of carbs: sugars, starches, etc. It’s a big part of our diet. And when they hit the bloodstream, fast and in quantity, our blood sugar spikes higher than is healthy. As discussed in the nutrition page, we at least come with a regulator to dampen the sugar spike. Your pancreas releases insulin. And the problem there is that insulin inhibits polysis, the process whereby the body burns fat for fuel.</p>
                    <h3>Carbs During Workouts?</h3>
                    <p>But it has further implications for endurance athletes. We worry constantly about fueling our workouts, our races. There’s this huge industry built up around sports drinks. But much of it is nonsense. First, the body normally has 1,200 to 2,000 calories stored in the muscles, blood stream and liver, ready to go. That’s between 2 to 3 hours of demanding activity. Going out for an easy 10 mile run? Figure you’d better takes some carbs along to fuel the run? Forget it. Completely unnecessary. You’ll be fine. If it’s a hot day and you’re sweating, some water with electrolytes will help enormously. Carbs? No. But here’s the really interesting piece of the puzzle. In addition to the glycogen stored in the muscles, your body can use something called the Krebs cycle to fuel the muscles by burning fat. And your body has 80,000 calories stored as fat. (Without being too cute about it, some bodies have even more fat available.) Imagine being able to fuel your endurance workouts with a nearly limitless supply of fat. How do we encourage the body to burn the fat instead of relying heavily on glycogen? First we need to stop the flow of insulin by avoiding the sugar spikes. No insulin rushing to the rescue and polysis can happen. The second thing we can do is to teach the body to get good at burning fat during exercise.</p>
                    <h3>Two Anaerobic Sources of Energy</h3>
                    <p>"Anaerobic," of course, means <em>without oxygen</em>. The most "immediate" (that's also the term the use to describe it) way to get some quick energy is the ATP/Creatine Phosphate System. It's quick, but you only can go for about 10 seconds on it. Then there's the "short -term" energy system (glycolysis). This can't burn as fast and leaves an unpleasant acid in the muscles. But you can go for as much as four  minutes before running out of gas. While a minute amount of anaerobic activity is going on all the time, it only becomes a significant portion of your energy supply at the very highest level of exercise.</p>
                    <h3>Two Aerobic Fuels</h3>
                    <p>The final energy system is aerobic, or <em>with oxygen</em>. And there are two fuels the body can turn to. The truth is your body is always burning both fat and glycogen during exercise. It’s the percentage that varies based on two variables. The first is how fast you’re going. The faster you go, the more the body relies on the faster sugar burning process. In a body which is good at burning fat the graph showing fat burning and glycogen is like so:</p>
                    <Row>
                        <Col>
                            <div style={{ width: '50%' }}>
                                <Image
                                    src='/Triathlon/FatGlycogen.jpg'
                                    alt='FatGlycogen'
                                    fluid='true'
                                    align='left'
                                    className='picture'
                                />
                            </div>
                            <div class='pull-right'>
                                <p>with the blue descending line (upper left to lower right) representing fat burning and the red ascending line (lower left to upper right) representing glycogen burning. The left side of the graph is slow exercise, the right side is fast exercise. As the exercise intensity increases the fat burning percentage gets smaller and the glycogen burning percentage gets bigger. During slow endurance exercise fat burning can be a big percentage of your energy source. If you’re exercising close to full out, you’re almost entirely burning glycogen. So speed is one variable influencing the percentage of fat to glycogen. The other is how well your system is adapted to burning fat.</p>
                            </div>
                            <h3>Running On Fat</h3>
                            <p>So here’s the point we’ve been moving toward. Slow easy exercise can rely largely on burning fat. The more you do of it, the better you'll get at burning fat. This assumes you’re not ingesting tons of sugar before and during your workout because you think you need to do so in order to sustain the exercise. Do that and the sugar levels get too high, the insulin kicks in and polysis is inhibited. Exactly what you don’t want. Even if you don't eat too much sugar before you exercise, do you really want any sugar hitting your blood stream as you start your exercise. If given a choice the body will always burn sugar over fat. It's easier and simpler. If you want to burn fat, don't push the body to burn sugar. (In a moment I'll talk about a diet that avoids carbs for this reason.) Some of your training should be at an easy pace and all you need in support is some water and electrolytes. And in cold weather you hardly need that. The more you exercise in this fashion the more your body is able to go for hours utilizing an almost limitless supply of energy. During an endurance race your pace will be faster than this easy training pace. And your glycogen burning process will be part of how you make your way. Replenishing some glycogen during a marathon or long triathlon is a great idea. But you don’t want to overdue. You also want to avoid the GI distress so common among long-course triathletes. GI distress happens because your blood is needed by your muscles and is not available to the stomach. So the sugar you’re forcing yourself to down sits there and makes you ill. Finally, on top of all these benefits on race day, if during the months of training you’ve been eating properly, you’ll have lost some weight. Which in itself will have made you faster.</p>
                            <h3>Warning</h3>
                            <p>Not everyone in the endurance coaching world agrees with this focus on fat. I think it's worth mentioning that this is a debate that has been going on for 40 years that I know of. I can remember running the nine miles to work each morning in the 1970s without first eating breakfast. I wanted to force my system to rely on fat burning. These days I tend to have a small amount of low glycemic food before going out on an early morning run just because my  blood sugar is too low after  12 hours without food. But if your sugar levels are normal when you start to exercise and you've got anything under an hour and a half at an easy pace, I don't think you need to keep feeding yourself to keep going. Yet there are many who still believe in a steady supply of sugars as you exercise and some of those folks are quite knowledgeable. The fat-burning proponents could be wrong. You get to decide what makes sense to you.</p>
                            <h3>When Sugar Does Makes Sense</h3>
                            <p>Keep in mind,&nbsp;when doing a high-intensity effort&nbsp;which burns lots of glycogen and modest amounts of fat, replenishing sugar does make sense. It's the kind of thing you're going to need to do in a marathon&nbsp;or long triathlon. So getting used to digesting sugars when you're doing high-intensity efforts is a great idea. In fact training is when you&nbsp;should be finding out how your gut reacts to food. Does a little high glycemic sugar water work best? Can you down a burrito and keep going. Experiment.</p>
                            <h3>Eating</h3>
                            <p>So how do you make all this happen? A healthy diet is key.  The plan suggested by US Olympic dietician and triathlon coach Bob Seebohar in “Metabolic Efficiency Training, Teaching the Body to Burn More Fat” goes as follows. Get yourself a piece of paper and make 4 columns. Label the first column Lean Protein and Healthy Fats. Label the second column Fruits and Vegetables. The third column is Whole Grains and the final column is Misses. Now in the first column make a list of foods you like that are Lean Protein and Healthy Fats. Your list might include: Chicken, Turkey, Beef, Fish, Lamb, Pork, Nuts, Nut Butters, Skim Milk, Humus, Avocado, Olive Oil, Flax, Eggs, and so on. In the second column list your favorite fruits and vegetables. Fill in the third column with Whole Grains and, oh heck, you don’t really need to fill in the fourth column.  It’s everything else. All the stuff you know isn’t good for you. And don’t delude yourself. Plain yogurt is good for you and goes in column 1. Yogurt spiked with lots of sugar is not what you want and goes in column 4.</p>
                            <p>Now it’s time to create your meals based on the phase of training you’re in. If you’re in the aerobic base phase, you want to limit your carbs.  Keep them to about 50%. Notice, that’s not a diet avoiding carbs. You’re getting plenty. Just not as much as most endurance athletes think they need. If you’ll pick one item from column 1 and one item from column 2, you’ll have a healthy meal. Now let’s say you’re in the training phase where you’re trying to build up speed and you’re doing intervals. That type of training depletes you glycogen stores quicker than the aerobic training did and you’ll need to up your sugar intake, especially right after a fast training session when the muscles are crying out for additional sugars. Now you get to include some whole grains in there as well. The result of all this is a very healthy diet, a more fit and trim body, and an engine that can go long distances without difficulty.</p>
                            <h3>Timing</h3>
                            <p>I've played with Seebohar's approach and mostly enjoyed the experience. I don't follow it religiously. I do avoid high doses of carbs when the body doesn't need them, which is most of the time. There is one moment when carbs <em>are</em> really needed. When you've just finished a workout, your muscles have depleted the glycogen supplies and are just crying out for replenishment. Here's my routine. I get in from my run and I fix myself a large glass of orange juice with protein, fiber and a pinch of creatine mixed in and I down that with some cashews (it's this strange addiction I have). If you think about it, there's nothing unhealthy about what I'm eating. But it is high in sugar. This is the best possible moment to eat such a meal. The sugar will go straight to the muscles and I'll avoid the sugar spike. (Also keep in mind that adding protein to the OJ will slow down the sugar absorption just a tad. And orange juice has a surprisingly low glycemic index.) Another option is chocolate milk. This is a small piece of shared humor amongst endurance athletes. "Time to hit the chocolate milk," and we all sort of smile to ourselves. It happens to have the perfect ration of sugars to protein that you need after a workout. We get to justify our sinful behaviour. (They actually did a 2011 study on this at the University of Texas in Austin. The control group got a carb drink after exercise and the test group drank chocolate milk. The chocolate milk group gained more lean muscle and lost more body fat. It's not that chocolate milk is the only way to get some protein after a workout, but it's a very pleasant way to satisfy both needs after a workout.) Or if I'm going to break out of Seebohar's guidelines and have some cereal, I'll have it after exercise. The odd thing is, the muscles get lazy after a couple of hours and lose interest in replenishing the muscle's sugar stores. Their rate of replenishment is much less thereafter. So you need to eat something as soon as your finished exercising, the longer you wait, the less your muscles will get the glycogen refill they need. I'll also add that this is when I stretch, right after exercise while my muscles are warmed up. So you've got to imagine me on the floor stretching with my orange juice and cashews beside me. Not a normal life.</p>
                            <h3>Protein</h3>
                            <p>You'll notice I added some protein to the orange juice. Did that sound gross? It's actually completely undetectable. I think a lot of Americans eat more protein than they need. But I also suspect that many athletes get less than they need. When you're exercising your muscles are (I'm not sure how to say this in a pleasant way) damaged. Ouch. Athletes are constantly stressing their bodies and then rebuilding them even stronger. The body is stupid enough to cannibalize itself to meet its protein needs. If some part of you is demanding protein and none is available, muscle that doesn't seem to be in high demand will be broken down to provide the protein. So unless you're willing to sacrifice your lean muscle mass, you need a steady supply of  protein. The recommendations I trust are from .45 to .72 grams of protein per day per pound of body weight. If you're doing a half-hour of exercise a day, the lower number would probably be fine. If you're doing two hours and day and lifting weights, go for the higher number. For me it's 110 grams. That's a number I can easily fall short of, so I keep a supply of Whey Protein Isolate on hand that I add to  some of my drinks. There are other forms of protein. Micellar Casein protein takes longer to digest which means it's perfect for taking before you go to bed so there's a steady supply of protein overnight. Unfortunately it's not tasteless like the Whey Protein Isolate, so you've got to really want it or hide the taste somehow. The protein in the stores is pretty expensive. I've found a fellow on the web selling it in bulk at very reasonable prices. Check out <a href="http://www.musclefeast.com/" target="_blank" rel="noopener noreferrer">Muscle Feast</a>.</p>
                            <h4>What To Eat To Restore Glycogen</h4>
                            <p>One of the most common mistakes people make who are trying to lose weight is to reward themselves for exercise. They'll run for half an hour and then reward themself with a muffin. I once eyed a chocolate muffin in a grocery store. Man did it look good. Then I checked the calories: 500. With a heavy heart I put it back. But imagine burning 300 calories in a 30 minute run and then rewarding yourself with a 500 calorie muffin. This is a plan doomed to failure. Yes, you should eat something with sugar in it after exercising. But it should be part of a healthy diet, not a <em>reward</em>. So grab&nbsp;some chocolate milk.</p>
                            <h3>Creatine Monohydrate</h3>
                            <p>Creatine speeds recovery after your workouts. The recommendations are 0.1 grams of creatine per kilogram of body weight daily, ideally immediately after training. For me (148 lbs.) that amounts to 7 grams.</p>
                            <h3>Caffeine</h3>
                            <p>Yes, caffeine has been shown to lower your perceived effort during a race, it all seems easier. You will perform better, and it's the one drug nobody seems to object to. But it really is a very powerful drug and I choose to avoid it 99% of the time. The one moment when I'll take a caffeine pill is right before a race. More on that in the section on race nutrition.</p>
                            <h3>Fish Oil</h3>
                            <p>Fish oil helps deal with the stress of exercise. I take it. Do your own research and figure out if it makes sense for you.</p>
                            <h3>Eleutherococcus Senticosus</h3>
                            <p>One of the articles I saw recently was entitled "Research You Can Use: Endurance-Enhancing Herbs, separating Fact from Fiction." It told how the Chinese herb "ciujia" (Eleutherococcus Senticosus) could increase endurance in athletes. It mentioned a web site that listed the studies to support the claim. When I typed in the URL provided I was redirected to a company selling the herb. Tricky! They did include a list of studies. However, when I did my own search for studies I found results which showed no improvement with the herb. I always trust studies which show no result more than I trust studies claiming to have found the next wonder drug. Studies which show no result rarely have a profit motive. Studies which show amazing results sometimes do. The article has the stink of someone trying to sell product. For what it's worth, Eleutherococcus Senticosus is available from plenty of manufacturers. I've decided not to bother with it. I decided to mention this because you will hear all sorts of claims about miracle herbs. I strongly encourage you to do some serious research before accepting ad copy. Go back to the original research by doing an internet search. Don't believe everything you read.</p>
                        </Col>
                    </Row>

                </Col>
            </Row>

        </Container>
    )
}