import React from 'react'
import { Container, Row, Col, Image } from 'react-bootstrap'

import TriathlonIndex from "./TriathlonIndex"

export default function TriRun() {

    return (
        <Container>
            <Row>
                <TriathlonIndex />
                <Col>
                    <Row>
                        <Col>
                            <div style={{ width: '50%' }}>
                                <Image
                                    src='/Triathlon/TriRun.jpg'
                                    fluid='true'
                                    alt='TriRun'
                                    align='left'
                                    className='picture'
                                />
                            </div>
                            <div class='pull-right'>
                                <h1>Run</h1>
                                <p>The picture on the left makes you wonder, <em>why is this man doing this to himself?</em> I was crossing a finish line, and I'd been pushing hard for the last three hours, and I was hurting. Sometimes running hurts. But I have other days when I'm just going out for an easy 6 miles when it's really a fun adventure. I pay a price for that. To be able to think to yourself "easy 6 miles" requires a certain perspective. You get that by going out for a 20 miler once in a while. Then 6 sounds like a piece of cake. And it actually is. It's what your body has been trained to do and it feels like the most natural thing in the world. And knowing that, knowing that you can run 6 miles and have it feel like a breeze, is priceless. It changes who you are and how you see the world. It'll put a smile on your face.</p>
                                <p>Yes, sometimes it's hard. Sometimes you're tired. But a life that is completely easy lacks something important. I think we need a little hard, a little adventure in our lives.</p>
                                <h3>Getting Started</h3>
                                <p>The standard introductions to running says, "Get yourself checked out by a doctor, buy yourself a good pair of running shoes, and then just do it." I think that's completely wrong. I think getting yourself checked by a doctor is something you should do on a regular basis. But I worry that people will think that means you shouldn't start running unless you're already fit. The worse shape you're in, the more you need to get yourself moving. With that said, yes, find out from your doctor if there are special problems you're facing and adjust accordingly. But it seems to me the warning ought to be, "Before beginning a program of sitting on the couch all day with the resultant risk to your health and fitness, consult a physician to make sure this won't cause serious problems for you."</p>
                                <p>I also have problems with buying a good pair of running shoes. If fact, I have all sorts of problems with running shoes. The more you encase your foot in big supportive cushioned shoes, the more likely it is, in my opinion, that you'll have problems. See if you can find something in your closet that's simple and flexible without a lot of thickness in the sole to get yourself started. Put off buying a new pair of shoes until you know what you're doing. And before you buy the shoes read <a href="/Triathlon/TriShoes.html">this</a>. And, finally, don't <em>just do it</em>. Below you'll find some guidance on how to run. Take the advice seriously and work at it. Do not assume you already know how to run well. Take the time to pay attention to your running in the beginning and your efforts will pay wonderful dividends. You'll make it much less likely that you experience aches and pains and problems down the road.</p>
                                <p>I've talked to people who assume that because they can't run continuously, they never could. But no one starts out able to run miles on end. No one. Everyone starts out at the same place. Everyone. You run a block or two and you're panting already. You're stuck walking the next block. That's how it begins for everyone, no exceptions. If you're in really bad shape, then you've got to be extra careful. Maybe in the beginning you just walk. Or you walk 90% of the time. Pay attention to what you're body is telling you and adjust accordingly. Pain is not something to be toughened out. It's a warning to back off.</p>
                                <p>There was a wonderful little piece of advice in Runner's World a while back. Do you want to get started as a runner? Well&nbsp;then, stop what you're doing, put on a pair of shoes, walk out the door, and start running. When it stops being fun, stop and walk home. You&nbsp;have just become a runner. You're not one of the hotshots who'll win the races. But you're now officially on the path and you're one of us. You've just got to go out the next day as well.</p>
                                <p>I started running because I wanted to be an athlete. I'd been a bust athletically during my high school days, and that feeling of inadequacy had carried into my adult life. I knew I had to do something about it. I decided that if I could run a marathon, I could call myself an athlete. No skill required, coming in last wouldn't matter; I just had to go the distance.</p>
                                <p>And so I became a runner. Equipment is minimal, something on your feet and a place to run is all you'll need. I'm lucky enough to live in Evanston, Illinois, so I've always had Lake Michigan to run along. The hard part is putting the shoes on and getting yourself out the door. Then you just do the best you can and trust the process, which means you have to take it easy in the beginning. There are three adaptations that happen when you run. Your cardiovascular system improves its ability to transport oxygen. Your muscles improve their ability to use the oxygen. And the collagen of your body toughens up. Meaning that gradually your body becomes able to stand the stress of longer distances without hurting itself. But give it time. You can't go too slow in the beginning. You can go too fast. It is not uncommon for runners to overdo and hurt themselves. So you start at an easy jog. When you get winded, you walk for a ways. When you feel recovered, you run again. You limit your mileage. So what if you only cover a mile or two each day for the first month. That's fine. When that starts to feel too easy, you'll go farther, but it cannot happen overnight.</p>
                                <h3>The Importance of Recovery</h3>
                                <p>Getting stronger is about stress and recovery in equal measure. You tell your body about the increased demands you'd like to be able to place on it. You give your body time to recover, to make the changes requested. Stressing your body doesn't make you stronger, it just makes the request. It's the recovery, the lying around afterwards, that actually makes you stronger. Which means you should always feel free to take a day off from the running. A perfectly fine schedule would be to alternate run day, rest day, run day, rest day. When that gets too easy, you can start running every day. But it's always smart to keep a day off in your schedule so you don't overdo. If you'd like some motivation to spur you on, get a subscription to Runner's World or buy the book <em>Born to Run</em> by Christopher McDougall (can't recommend it enough). And then just be patient with yourself.</p>
                                <p>Gradually the miles get easier. You find that running 4 miles is no big deal. You almost feel like it's not enough. Next thing you know you're running 6 miles and can't figure out why your friends go into shock when they hear it. A secret pride will grow in you. You'll feel like an athlete. Your body will fit you better. Running creates a well within you. There is a reserve there you can call upon when needed. Your will has been polished.</p>
                                <h3>Running Form</h3>
                                <p>Here's what I look for in evaluating running form:<br></br>
                                    1. How much up and down motion is there? If the runner is leaping into the air, they’re doing an awful lot of wasted work in addition to the extra punishment their body goes through as they land. Sure they're only bounding into the air an inch on each stride. But imagine doing that on every stride for 6 miles. They've climbed pretty near the Empire State Building with nothing to show for it. This leaping into the air is often an attempt to increase speed by increasing stride length. But it's the wrong way to do it. And leaping brings on our next problem.<br></br>
                                    2. Does their forward foot extend before them? If so, they will land with their leg straight and extended. The heel will strike first and their stiff leg will absorb the shock of the landing. This diminishes their forward momentum and adds stress to the knee and hip joints. It’s better to land on the front half of your foot with the weight over the foot. These first two points are the difference between leaping and rolling like a wheel.  Rolling is better. Having the runner focus on faster footfall per minute can help enormously in correcting this. Much more on this shortly.<br></br>
                                    3. Arm motion should be a simple forward and back with elbows at about 90 degrees.  Hands relaxed but not floppy. If your arms cross over your midline, you're doing too much twisting of your torso.<br></br>
                                    4. There’s a slight tilt to good running. It’s not a bend from the waist, but from the ankle. The whole body angles a little forward. It’s almost as if you’re falling forward and each footfall catches you and moves the wheel along. I think of this as  leading from my hips, because that avoids my tendency to slouch when I get tired. But the reality is, I want my body to remain fairly straight. My hips a half inch ahead of my toes, my chest a full inch ahead. If you pay attention as you lean, you'll find a position when the running seems to get easier. There's less effort involved. Always look for less effort in your running. How can you make it feel easy?<br></br>
                                    5. When the leg comes forward the knee will bend, simply due to physics. It's easier to move a weight through an arc when it closer to the fulcrum. There's a formula for this. (And that's why you keep your elbows bent.) It won't be much of a bend when someone is running slowly. But as a runner picks up speed, the bottom of the leg will actually be parallel to the ground as it come forward.<br></br>
                                    6. Pick up your stride rate. There's no absolute rigid number for all people, but I would suggest seeing how close you can get to having a foot to touch the ground 180 times each minute. You can go above 180 if that's comfortable for you. If you get yourself up to 180 for a month and it never manages to feel normal for you, then back off until things feel right.&nbsp; A high stride rate  will help you avoid your leg extending in front and slowing you down. It leaves you rolling instead of leaping.<br></br>
                                    7. Remove the extraneous. Any motion that does not move you forward is not needed.<br></br>
                                    8. Keep your feet straight. If your feet turn out to the side as you run, you'll lose a quarter-inch on every stride. What's a quarter-inch? Over the course of a 10K, maybe 250 feet.<br></br>
                                    9. Your feet should land under you, not off to the side. If you were to run through sand, you should be able to draw a line along the footprints and have the inside of each foot touching the line. Which is why if you've got good running form and wear big heavy running shoes with those wide flared bottoms designed to stabilize you, you will sometimes unpleasantly graze the inside of your ankle with the shoe edge.<br></br>
                                    10. Don’t express how tired you are. Usually people do this by crunching up and leaning from their waist. To do so will  impair your breathing, alter your stride and leave you less than upright. Smile and keep your head up.</p>
                                <p>The most important point here is that, instead of reaching with the heel, land with your foot beneath you. It’s like you’re rolling on a wheel, and your legs are the spokes of the wheel. (And since you only have two spokes, you keep reusing them by sneaking them forward once they’re no longer needed.) So instead of leaping up and forward and landing on the heel, you keep yourself on an even keel and roll. Can you see how the feet might have to increase their rate of touching down in order to do the rolling?</p>
                                <p>In fact, this is what makes changing to this style of running not so impossible. At the University of Wisconsin they took a group of runners, put them on treadmills and measured the stresses on their bodies. How much impact was hitting the knee or their hip each time the heel landed? Then they asked those same runners to increase their stride frequency (the number of times each minute the feet hit the ground) by 10%. When the runners did so, they no longer had time to reach out with their heels and they started landing more flatfoot with their feet under their center of gravity. And lo and behold the impact on their joints diminished significantly. The force absorbed by the knee went from an average of 9.2 (J/kg) to 6.1. Notice that this was without any other changes in their form. They weren't landing on their toes and absorbing shock in that fashion. Imagine how low the number might get with really good technique. Later they asked the runners to slow their normal stride rate by 10%, that same force went all the way up to 13.5. More than twice the stress on the knee as when they were striding 10% faster than normal.</p>
                                <p>Finally, they've tested runners in Kenya who grew up running barefoot and found that their impact was just 33% of the normal impact for people landing on their heels. There's a form of running beyond this, but this is the basics.</p>
                                <p>There's another way to get at this. Take your earbuds out and really listen to sound of your foot striking the pavement. The Harvard Medical School and the National Running Center at the Spaulding Rehabilitation Hospital studied the relationship between the force of the footstrike and the likelihood of injury. Yep, the more noise you make with your foot landing, the more likely you are to injure yourself. So play with it. Can you find a way to run that makes less noise. Your body will thank you for it.</p>
                                <h3>Shoes & Form</h3>
                                <p>When I started running around 1970, shoes were pretty simple: a thin slab of something similar to a flip-flop with a colorful nylon top. The shoes I preferred were by Tiger (now called Asics) and Nike wasn’t around. I liked the shoes and they worked fine. Over the years the shoes got fancier and heavier and more expensive. The shoe companies kept building up the heel to absorb the shock of running. And I guess we all assumed the shoes were getting better. I remember when I saw an African runner, Abebe Bikila, running barefoot and winning the Olympic Marathon in 1960, I couldn’t fathom it. Barefoot? On concrete? I still can’t imagine doing so. But there are people urging us to try barefoot running, and the points they’re making are completely valid. The problem with most running shoes is that they’re trying so hard to protect us from the pounding. And there <em>is</em> pounding in running. Thing is, this may be a case of which came first, the chicken or the egg? When you build up the heel on a shoe to provide adequate protection when you land, you make it very difficult not to land on the heel. Many runners land on the heel with the foot extended before them, and the shoe’s heel helps cushion the impact. But that cushioning of the impact is another way of describing a braking of momentum. When the foot lands extended and the heel absorbs the impact, you’ve diminished your forward momentum.</p>
                                <h3>The Final 10%, Forefoot Running</h3>
                                <p>If you're landing midfoot with your weight over your foot. You've got 90% of the package. There's another possibility beyond that. If you've ever tried running barefoot, you probably found yourself  cushioning your landing by touching down with the ball of your foot first to ease into the landing. Your heel doesn't touch at all. Sprinters run on the balls of their feet. I spent 40 years landing midfoot. When I first tried running as a sprinter would, it was a revelation. I was running faster than I ever had before and it felt light and easy. You can't imagine what a shock that moment was. <em>I've been running for 40 years and it never occurred to me this was available???&nbsp; </em>It made me a believer. Except it's not that simple. I found I couldn't maintain that sense of ease for more than 50 yards. My toes started to feel it. Going past a quarter mile and my calves hurt in a not-good way. I'm convinced that landing on the ball of the foot is the an excellent way to run, possibly the most natural way to run. We evolved without thick-heeled running shoes and I suspect running as if you are barefoot is the closest to letting the body function as it was born to function. But I'm also convinced you have to be incredibly careful if decide to go down this road. If you didn't grow up in Africa running barefoot, you're body has adapted to an alternative approach. It isn't ready to just switch gears. After  years of working on it off and on, I'm finally able to run a mile and a half landing on the ball of my foot without being sore as heck the next day. But I still do most of my running my old style. While I'm excited about starting to lengthen the portion of my runs done in the "barefoot" style, making that transition has been difficult for me. I'm certain "barefoot" running is what I want for myself in the future. But it is has been a struggle getting this far and I intend to continue to be very cautious. In my own case I have very little padding between my foot bones and the skin (a condition called metatarsalgia). There's a chance I may never quite make it to the promised land. But I do believe the body adapts, and I'm going to keep working toward that goal. If you decide to go this route, go easy on yourself and don't expect the change to happen overnight. It may take six months, it might take a year. Even if you're an experienced runner with thousands of miles behind you, you're likely to think you can make the change overnight. Most who take that approach end up injured.&nbsp; This is a different stress to the body and you need to give yourself time to adapt. While they've measured some stresses on the body as being less with "barefoot running," they've also found that the stress on the achilies tendon goes up 11%. And if you feel like you'd prefer to stick with midfoot running, you have my blessing.</p>
                                <h3>"Barefoot" Shoes</h3>
                                <p>For what it's worth, I don't run shoeless. There are folks who do, I'm just not ready to go there. Trouble is, most shoes make it almost impossible to run on the balls of your feet. The heels are so thick that even if you're trying to get the forefoot down first, the heel is what makes contact. Imagine a woman in stiletto heels. Even if her foot is in a great position for the forefoot to reach the ground first, that heels going to be the contact point. You have to get yourself a pair of shoes without a heel if you really want to do "barefoot" style running. So I wear a pair of shoes from Altra that have no heal but do have some cushioning throughout the shoe. If you hate the cushioning there are shoes from Vibram and Merel with protection but no cushioning. I've got such shoes but they mostly sit in the closet. I like a little cushioning. A recent study from Rodger Kram's lab published in <em> Medicine &amp; Science in Sports &amp; Exercise	</em>found that running in shoes took less energy than running barefoot (though the heavier the shoe gets the more the advantage disappears). The point being, a little cushioning helps you run better. A great deal more on shoes is available <a href="/Triathlon/TriShoes.html">here</a>.</p>
                                <h3>Cadence</h3>
                                <p>So one way to improve your form is to pick up your cadence. Shoot for about 90 landings of say your left foot per minute. You could do this by checking your watch for 15 seconds and counting how many times one of your feet touches the ground in that time. Multiply by 4 and you’ll have your stride rate. (If you’re wondering, yes, the actual number of times either one of your feet touch down will be twice your stride rate. But it’s easier to count this way.) I actually bought myself a little clip-on metronome (Seiko DM50S Clip Digital Metronome) and matched its beat (180 bpm) for a while when I was working on my cadence. When you first pick up your stride rate it will probably feel choppy and like you’re trying harder. But I think once you’ve run this way for a while, it will seem easier. The "180" isn't carved in stone for everyone. The taller you are, the more likely that you'll need a fraction of a second longer for each stride. After practicing at 180 I pulled back to 178 for a while. But then I bumped it up again. Who knows where I'll end up. After you've practiced at 180 for a while, play with the pace until you find what's most comfortable for you. The really fast runners can get up closer to 200.<br></br>
                                    <br></br>
                                    Have you noticed how the African runners are so dominant in the distance running events? Most of them grew up running on dirt roads without shoes. I was down helping out at the Chicago Marathon in October of 2010 at the mile 16 aid station. The wheelchairs came by first. Then the cry went out, "Here come the elites." Eight little men from Africa came racing by. (I will mention that all of them wore running shoes. But I assume they've chosen very minimalist shoes, and that for their formative years they had no shoes.) As far as I could tell they were all landing on the balls of their feet. They weren't around for long, but I managed to count the footfalls for what I hope was 15 seconds. Looked about 96 strides a minute. (Wide margin for error here.) Then they were gone. And then nothing. The rest of the field took perhaps five minutes to start showing up. They're that much faster than us. You find yourself wondering why. <em>Maybe it's genetics or training or something</em>. But they've tested all this out. They don't have exceptional VO2 Max or any other physical factor. Our coaches have studied this till they're blue in the face, trying to figure out their secret. The only thing that's exceptional about them is their running form. These guys are smooth. Maybe if we’d just go over to Africa and give the kids thick-heeled running shoes early enough we could slow them down a bit.</p>
                                <h3>The Warning Repeated</h3>
                                <p>If you've been a heel striker for many years and now want to try touching down on the balls of your feet, make the transition gradually. Just because you can run for miles, doesn't mean you body is ready for long runs in this fashion. It's quite common for people to switch to "barefoot running" thinking it will allow them to run injury free, only to injure themselves in the process of making the transition.</p>
                                <h3>How To Train</h3>
                                <p>There's a debate that goes on in running: quality or quantity. In other words, do you run modest distances very hard or do you run long distances easy? Most runners rely on both methods of training. But people do tend to find themselves leaning toward one approach to training over the other. I have two stories to tell you.</p>
                                <p>First I'll tell you my experience with speed. I was really slow in high school. Went out for the track team. Couldn’t even run a 7 minute mile. I was useless to the team and a month later I quit. Then in my 20s I started running (1970s). I adopted a theory called Long, Slow, Distance. Often shortened to LSD. (I think using the word “slow” was poorly chosen. “Easy” is a better way to say it. You don’t need to go slow. But you do need to go at a relaxed pace that you can maintain over distance without strain.) So I never trained for speed. Never worried about it. But I did put in the miles (50 to 60 miles a week at this point). The day of my first attempt at the marathon I gathered with 70 other people at the starting line. (This was in the 1970s before distance running had become part of normal life. That “70” was pretty much the entirety of long distance runners in the Chicago region.) So the gun goes off, and we all take off. We were running pretty much as one big pack. I felt great. It was a cold day. I was psyched. We’re all breezing along with not a care in the world. We get to the two mile mark, and they’re counting out the time. (We didn’t all have stop watches on our wrists back then.) “11:58, 11:59, 12 minutes.” I had just run two miles in twelve minutes. That’s six minutes per mile. I’d never run anywhere close to that in my entire life. It was shocking and disorienting. Understand, this is without speed-work, without reps. I had gotten faster just because my body had adapted to aerobic running. Knowing what I know now, I probably could have gone a shade faster with some speed work. But understand how far I’d come without it.<br></br>
                                    <br></br>
                                    I’ll go ahead and mention how the marathon turned out. I knew the second I heard the time I was in trouble. I’d burned through way too much of my glycogen stores way too fast. If I’d gone slower a lot of that glycogen burn could have been fat. So at mile 22 I was in trouble. I literally couldn’t operate my body. I felt like a puppet and someone had cut the strings. I was staggering and unable to walk upright. There was one other factor at play: it was a cold day and I hadn’t wanted to overheat, so I had very little on. The place where we started the race was sheltered and I thought I had the right amount of clothing on. But within minutes we were running along open fields and the wind was really blowing. By mile 22 I was shivering and frozen. So I don’t know whether running out of glycogen or the cold did me in, probably a combination of the two, but that was it for me. They picked me up and drove me the last 4 miles to the finish. &nbsp;If something similar happens to you, keep in mind that I kept at the running and two years later ran a 3:17 marathon. So setbacks are only setbacks. They’re not terminal. Plus now I've got a story to tell. Stories are precious. And in the long run you'll find you don't care much whether you're telling about success or failure. In fact the failures make for better stories.</p>

                            </div>
                        </Col>
                    </Row>
                </Col>
            </Row>

        </Container>
    )
}