import React from 'react'
import { Container, Row, Col } from 'react-bootstrap'

import TriathlonIndex from "./TriathlonIndex"

export default function TriRaceNutrition() {

    return (
        <Container>
            <Row>
                <TriathlonIndex />
                <Col>
                    <h1> Race Nutrition </h1>
                    <p>They say the fourth discipline in Triathlon is fueling. That's because month's of training can go down the tubes if you run out of glycogen. But it's only a serious concern if you're going for long distances. In a sprint triathlon it's irrelevant. You could take in some water and electrolytes and be home free. That does not make it a good idea. Every race should be a learning experience. In the shorter races fuel the same way you would for a longer race just so you'll know what works for you.</p>
                    <p>In a longer tri or marathon, it is easy to run out of steam. They like to call it hitting the wall or bonking. You can literally reach the point of not being able to run any further. And it's not a matter of will-power. You simply can't operate your body. So what improves the odds that you'll hit the wall? In a marathon there are three predictors that make it more likely:</p>
                    <p>1. You're male <br></br>
                    2. Expecting to hit the wall <br></br>
                            3. Never having run over 20 miles in your training regimen</p>
                    <h3>How Much Glycogen For A Marathon</h3>
                    <p>For the sake of simplifying the discussion, I'm going to talk about running a marathon instead of getting into the complexities of triathlon. But the concepts you need to consider are the same. To run a marathon requires 2950 kcal for someone weighing 70 kgrams (that's 153 lbs, if you weigh less it takes fewer kcal). So where do we get the calories (glucose) for a marathon. Well you've got some in your blood, except it's only about 20 kcal. Not a huge help. Your liver can store glucose, somewhere between 350 and 650 kcal. We're still not close to having enough kcals for a marathon, but notice that with  these two sources of glucose the fuel can be sent anywhere in the body you need it. You can also store glucose in the muscles. But it can't be moved from muscle to muscle, so we're only calculating the glucose you can store in your leg muscles. (Keep in mind that biking and running use different muscles. Depleting glycogen in your biking muscles does not mean you've depleted it in your running muscles.) It comes to approximately 1250 kcal. Though with perfect carb loading in a really well trained runner it's possible to get that up to 2270. <strong>(Please notice that while I'm encouraging you to get good at using fat, carb loading before a big race is can make a huge difference in how well you perform. It's not so much that you up your calories in the three days before the race, but that you shift most of your normal protein and fat intake into the carb category.)</strong> So our total of glucose available in a perfect world comes to 2940 kcal. From there you can see the finish line. In a less than perfect world it might only total up to 1620 kcal. That might leave you hitting the wall well before you got to the 20 mile mark. These values are the same whether you're running fast or slow. But glucose is not your only source of energy. You can burn fat. How much fat you burn is based on how well you've trained your body to burn fat and how fast you're going. The faster your pace, the more you'll have to rely on glycogen.</p>
                    <h3>Burning Fat</h3>
                    <p>Running the ideal race is a matter of setting a race pace for yourself that allows you to use up nearly all your glycogen stores, but not quite. They say fat burns in the flame of glycogen. You can't just run out of glycogen, hit the switch and revert to fat burning for the last few miles. Once the glycogen is gone, you're ability to burn fat falls apart.</p>
                    <p>Some examples might help. Let's say you weigh 155 lbs and need 3000 kcal to run a marathon. If you're running at 8 minutes per mile and burning 60% fat and 40% glycogen at that speed, then you only need 1200 kcal of glycogen to run the marathon. Even without perfect carb loading you've got that in your body. Now imagine that you're running 6:30 miles and burning 30% fat and 70% glycogen. Now you'd better have 2100 kcal of glycogen available. Possible, but not a given. One last example. You haven't trained for fat burning, you weigh 200 lbs and you're running at 7 minutes a mile. You're burning 20% fat and 80% glycogen. You'll need 3200 kcal of glycogen to make it to the finish line. That's just not possible with what you start out with.</p>
                    <h3>Fueling As You Go</h3>
                    <p>But can you add fuel during the race? A little, but it's not unlimited. The problem here is that the body is shunting all that blood to your legs and neglecting the needs of the stomach. You can pile the carbs into the stomach, but that's no guarantee they'll get digested. Unfortunately, the faster you're going&nbsp;(and thus the more glycogen you need), the less blood is available for processing food in your stomach. When you're going at an easy pace, it's much easier to take in sugars without problems arising.</p>
                    <p>The nature of the fuel you use also matters. Sometimes you'll find maltodextrin listed as a sports drink ingredient. It's a long-chain carbohydrate that needs to be broken down before it can hit the blood stream. Normally that's great. It means you'll have a slow steady supply of sugar instead of the quick sugar hit that can cause a blood sugar spike. But when you're racing you're pushing yourself harder than normal. All the blood is shunted toward your muscles and next to nothing is available for processing food in your gut. Maltodextrin, because it needs processing, just sits there. And the more you down your sports drink, the more the maltodextrin piles up in your tummy, the greater your gastric distress is going to get. The next thing you know you're on the side of the road puking. So you need a sports drink that uses sugars that don't need breaking down. Look for glucose (also called dextrose) or fructose in the ingredient list. A simple sugar doesn't need breaking down and can pass quickly into the blood stream. One kinda cool thing is that glucose and fructose use different transporters in the stomach. Either one separately has a rate of absorption around 1.2 grams per minute. But when the stomach is absorbing both together you can get up to 1.75 grams per minute. That comes out to 105 grams per hour. So a mixture of the two sugars seems like a good idea.</p>
                    <p>There also seems to be some relationship to weight, bigger people seem to be able to absorb more than smaller people. Some would say  that the maximum number of grams your body can absorb is one gram of carb for every kilogram of body weight. If that's true, 200 pound fellow in our example up above would only be able to absorb 90 grams per hour (smaller people even less). However, I don't know what  sugar was used to get these results, so I don't know if that's a real upper limit.</p>
                    <p>What you're looking for in a sport drink is fluid, some calories to burn (a mixture of glucose and fructose would be nice), electrolyte replacement, and maybe a little protein. For <strong>every 8 ounces of water</strong> look for maybe 15 grams of carbs, 110 mgs of Sodium, and a few grams of protein. You'd also like them to throw in 35 to 50 grams of Potassium, some Magnesium and Calcium. Don't think you can choose something with more than 15 grams of carbs and get even more benefit. The extra carbs will just sit in your gut and cause problems.</p>
                    <p>So figure out how many ozs of liquid your water bottle will hold. How many grams of carbs does that constitute? And figure out how many grams you want to down per&nbsp;hour. That tells you what percentage of your water bottle you want to go through each hour. Then consistently sip at your water as you ride your bike.</p>
                    <h3>Solids on the Bike</h3>
                    <p>I wish I were more clear about why this is so, but there seems to be fairly wide agreement that your digestive system works better on the bike than during the run. Solids that would cause trouble on the run are possible on the bike. You just seem to be able to process things better. Plus it’s not that hard to have food stored on the bike. Eat like you’re hungry. But keep in mind that digestion takes time. If you’re going to try some solids, do it in the first half of the bike. If you leave it until the last hour, you’ll be trying to digest it on the run and you might get into trouble.</p>
                    <h3>Water</h3>
                    <p>The problem with water is that you don't sweat water. You sweat water plus electrolytes. If you just replace what you've lost with water, you'll run out of the electrolytes which control just about all of the neural firings and muscle&nbsp;contractions. And if you just keep piling in the water you run the risk of progressive hyponatremia, the water overload that can actually kill people.</p>
                    <h3>Gels</h3>
                    <p>Gels contain a mix of sugars and electrolytes. They must be diluted with water to get absorbed and be useful. If you wash them down with an&nbsp;energy drink containing sugars and electrolytes, they're not getting diluted like they need to be. Go with one or the other, not a combination. Use a gel plus a glass of water, or use a sport drink. Don't combine. Keep in mind, you're even allowed to eat real food. Just make sure it's easily digested. For that reason, vegetables aren't what you need when racing.</p>
                    <h3>Caffeine</h3>
                    <p>Caffeine makes a race seem less arduous. The recommended dose is 3 milligrams for every pound of body weight taken 60 minutes before the race. But understand that caffeine is a powerful drug. Using it constantly every day as a stimulant strikes me as very unwise.</p>
                    <h3>Find Out What Works For You</h3>
                    <p>The thing is, we're all different. The best thing you can do is experiment. Try eating a chocolate chip cookie&nbsp;in the middle of a race-pace run. Do you soon feel like puking? I've heard of someone stopping for a hamburger and a Coke in the middle of an Ironman. For most that would be a disaster. For this guy it was exactly what he needed to feel human again. Some people have iron stomachs. Some people have to be incredibly careful about this stuff or they'll pay the price with GI distress. Imagine having both diarrhea and vomiting in the middle of a race. It's happened. Get this figured out before the race so it doesn't ruin your day.</p>
                </Col>
            </Row>

        </Container>
    )
}