import React from 'react'
import { Container, Row, Col, Image } from 'react-bootstrap'

import TriathlonIndex from "./TriathlonIndex"

export default function TriSwim() {

    return (
        <Container>
            <Row>
                <TriathlonIndex />
                <Col>
                    <Row>
                        <Col>
                            <div style={{ width: '50%' }}>
                                <Image
                                    src='/Triathlon/TriSwimFinish.jpg'
                                    fluid='true'
                                    alt='TriSwimFinish'
                                    align='left'
                                    className='picture'
                                />
                            </div>
                            <div class='pull-right'>
                                <h1>Swim</h1>
                                <br></br>
                                <p>When I got it into my head that I wanted to be a triathlete, I realized I'd have to learn to swim. Oh, I could swim across a pool, but across a lake? So for some time I dragged myself over to the YMCA and did my laps. I didn't look forward to it and didn't enjoy it, but I was determined. I'd swim 50 yards and then hold on to the side of the pool and pant for twenty seconds before once again launching myself into the weariness of it all. I promised myself that when I was finally able to swim continuously I'd buy myself a music system I could listen to in the water. In the end, I never did buy that music system. Instead I discovered the fascination and fun of learning to swim well.</p>
                                <p>I did this thanks to a fellow named Terry Laughlin. He's not the only one teaching this approach to swimming, but I think it's safe to say he's the most visible. The premise here is that the resistance of water is such a huge obstacle to overcome, that the quality of your swimming (the ease with which you can slip through the water) is every bit as important as your strength and stamina.</p>
                                <h3>This Takes Time</h3>
                                <p>Swimming is the toughest of the three disciplines to get good at. You can get so you can run a few miles after a few months. Riding a bike can happen even quicker. Becoming a quality swimmer takes years. It's a subtle skill, and after years of practice I still find myself finding ways to improve my stroke. On a regular basis I tell myself, <em>boy you've got a great stroke</em>. And then a month later I find myself looking back and realizing I wasn't quite as good as I thought I was. <em>Ah, but now I've got it</em>. Except a month from now I'll probably look back... You get the idea. I also think it's harder to build up endurance in the water. Don't know why that is. After a year you'll be able to run for a couple of hours without stopping. That&nbsp;level of endurance in the water will take several years. Most of this has to do with your ability to slip through the water with the least amount of effort possible. I was recently coaching a woman who had swum on her college team. The first time in the pool&nbsp;I spotted a few little details that I thought could be better. I shared what I could. She gave them a try and decided she'd rather stick with what she knew. Curious, I counted her strokes per lap. Low teens. Nice. I timed her for 50&nbsp;and realized she was faster than me. I'd had my say and decided I'd said enough. She'd paid her water dues already. Her stroke worked for her. There's something about putting in your time in the pool. Her body had found its way through the water.</p>
                                <h3>The Density of Water</h3>
                                <p>Have you ever put your hand out the window of your car and felt the air pushing your hand? Of course you have. Pretty forceful, isn't it? Well water is 784 times denser than air. So trying to fight your way through the pushback that water provides is quite a feat. But think back to your hand in the air out the car window. If you could keep your hand very flat you robbed the air of its power. Same with swimming. The flatter you can float through the water the better you'll do. Now think about floating, if you're just lying face down in the water, which part of you sinks? The legs, right? They don't have a lot of natural buoyancy. Your buoyancy is in your chest, your lungs are like water wings. Now imagine swimming through the water and your feet are trailing behind you a couple of feet below your head. You're not flat in the water, but at an angle. You're offering the water a great deal to push against. That's the problem in a nutshell. We're not really designed for swimming. Come to think of it, how the heck do fish swim? They don't even have arms or legs to propel themselves forward. But they're obviously shaped to offer a minimum resistance to the water, and they manage to twist their bodies through the water at remarkable speeds. Now it's hard to believe this until you've experienced it, but people can swim in a fashion that has some of the elements of what fish do. But it doesn't come naturally, and it takes some learning.</p>
                                <h3>Balance</h3>
                                <p>Let's get back to floating. You're face down in the water. How do you counteract the weight of the legs and keep them from shifting you into a slanted position? How do you stay flat in the water? What's above your chest? Well, your head. Anything else? Well, if you move your arms overhead so they're pointed out in front of you, you've  created some counterbalance to your legs. Plus they add length to your body and long ships can move faster through the water than thick chubby ships. It's a mathematical formula. Think of the difference between how they design racing ships and tugboats. This business of extending the length of your body is critical to how easily you'll slip through the water. So now we've got you lying flat down with your face in the water and your arms overhead. What happens if you lift your head? Your legs will drop down. If you think back to all the times you've been in the water, you'll realize this truth. It's like you're a teeter-totter. And your buoyant chest is the fulcrum. If the head comes up, the legs will go down. However, if you keep your face low in the water, maybe even pushing your head down a little bit, it acts as a counterbalance and the legs will stay up. One of the easiest ways to spot a good swimmer is to check out their heads. If all you can see of their head in the water is a little slice of the back, they're doing a lot of things right. It's on my list of things I think about:
                                    keeping my face looking straight down, immersed in the water.</p>
                                <h3>So What Else Do I Think About?</h3>
                                <p>I swim with my body tilted to one side or the other, at maybe a  45 degree angle, first left side down with left arm extended and then right side down and the right arm reaching forward. I'm rotating side to side. This rotation make it easy to lift my arm out of the water to bring it forward for the next stroke. The arm on the up side lifts, elbow in the air, and the hand slides straight forward, fingers almost skimming the water, very relaxed. The forearm is sort of hanging from the elbow. That hand enters the water at an angle, entering just beyond my head and in front of the shoulder. If you reach out way in front of you before entering the water, you're putting unnecessary stress on the shoulder joint. Overuse injuries can result. The hand enters at perhaps a 45-degree angle and then slides forward directly ahead of its shoulder. We're getting a little ahead of ourselves here, but this is the moment, with the hand knifing into the water, is when all the power happens. The down leg gives a little kick to help with the rotation, the lead arm pulls back, the body rotates toward the other side, the hand slices into the water. It's all connected. And if instead of knifing the arm into the water, you extend it gently over the water and just rest it on the surface ahead of you, you will lose much of that rotational power.</p>
                                <h3>Avoiding Pushback</h3>
                                <p>Of course, you don't want to create a lot of pushback from the water, so the hand must enter with as little disturbance of the water as possible. Excellent form results in very quiet swimming since you're not attacking the water but sneaking through it. When the arm reaches its destination it is directly in front of its shoulder maybe 6 to 8 inches beneath the surface. (I'm actually just guessing about the depth of my hand since I can't see it. If I can see it, my head is looking too much forward and not directly down.) The hand does not cross the centerline. Perhaps there's a little stiffness to the hand as I try and quietly knife my way through the water, but once in position it relaxes, palm down and fingers hanging. In that first moment I'm really reaching with that arm, extending through it. But then it relaxes and a little bend in the elbow happens as it prepares for the catch. And now it waits a moment. It does not want to pull back too soon. It wants the other hand to take its place and keep the vessel long before it leaves its post. This is your chance  to glide as the catching arm lifts out of water along your upper side. Enjoy it.</p>
                                <h3>Thrust</h3>
                                <p>Not until the other hand is knifing forward into the water does the forward hand begin its pull back through the water. And this is the moment when the magic happens. You'd think it's the arm pulling back against the water that propels you forward. And I'd be an idiot to deny that that's part of what happens. But it's not the magical part. Your body is rotating from side to side as you swim. If your left arm is stretched out before you and the right arm is lifting to enter the water, you're tilted maybe 45 degrees onto your left side. And as your right arm enters and replaces the left arm you'll rotate over onto your right side. And that moment of the corkscrew when you shift sides has the most amazing effect on your speed. If you do it right, you'll seem to spurt forward. If you just pull you hand through the water, not so much. I'm not sure I can explain it, but I know I've experienced it. It reminds me of what fish do. They swim from their core.</p>
                                <h3>Don't Push Down</h3>
                                <p>That bit about the fingers hanging down loosely is a Terry Laughlin suggestion. I at first decided it made more sense to keep my hand stiff and pointing straight ahead. I figured I was cutting back on the amount of resistance I offered the water. But then I noticed that the flat hand was a huge temptation. If it any moment I felt out of balance that hand was in the perfect position to push down and lift my head out of the water. Exactly what I'm trying to avoid. I found that when I let the hand relax, hanging down, palm facing back, the desire to push down went away. The pull with the hand must be back, not down.</p>
                                <p>The last bit of learning I had to do involved the elbow. You need to think of you entire arm as what pulls you through the water, not just your hand. If you pull your elbow back first with the rest of the arm following, you're presenting the knife edge of your arm to the water instead of the broad blade. (This is what they mean when they talk about a "dropped elbow.") Keep your elbow a little bent and wide as you pull back and you'll have a better purchase on the water. That way the whole arm pulls and not just the hand. You'll notice when you do it this way that it's much harder to do than when your elbow pulls through first. Which makes the wide elbow tempting to avoid. But it's harder precisely because you're catching more water and providing yourself a better forward pull. You may notice (I certainly do) that there's a temptation to relax the arm in various ways, just because it hurts less. Your arm and lats are tired and you've got some burning in your muscles and getting sloppy just plain hurts less. Even the slightest rotation of the wrist can allow more water to escape your hand, making the catch that much easier. I've had moments when I succumbed. But try not to. Practice swimming strong. Swim slower if you need to but don't let the elbow drop, keep the palm of your hand perpendicular to your direction. In the long run, this is crucial. When I've got a good purchase on&nbsp;the water it almost feels like the arm is stuck in mud and hardly moving. It feels like my body moves over the stuck hand, not the hand moving under the body. As your hand reaches the end of the stroke, see if you can bend the hand back and push back with your palm. You can even add a flick of the wrist at the very end. Make it a full long stroke. Don't be too anxious to begin the recovery.</p>
                                <h3>Breathing</h3>
                                <p>Breathing is tricky. The tendency is to lift your head to breath. But we already know what a bad idea that is. You've got to roll the head. Turn the chin back toward the shoulder. I even think about pushing the back of my head into the water as I do it. Yes, you risk getting a little water in your mouth if you do it this way. But one of the most important lessons you have to learn in the pool is that water won't kill you. It's just water. Maybe, if you're afraid of the water, it can get you in trouble. Panic a little bit and the next thing you know you're gagging and sputtering and coughing. But when I get water in my mouth, I hardly notice. My breaths only take a second and before anything bad can happen I've got my head face down in the water again. Do you think you can choke on water when your head is face down in the water? Can't happen. The water falls to the front of your mouth. Breath out even a little bit and the first thing that exits is the water. You can open your mouth underwater and, if you're face down in the water, the air in your mouth will keep the water out. I sometimes notice that my mouth is open underwater. It's no big deal. If you do manage to swallow a bunch of water, it can be a disaster, and I'll come back to this issue momentarily. But in modest amounts, handled calmly, water getting in your mouth is not a big deal.</p>
                                <p>So how do people get in trouble? When you're afraid you're about to drown the most natural thing on earth is to lift your head. And then the water really can go places where you don't want it. Of course, if you're afraid of the water all the logic in the world doesn't help. But there are exercises you can do to overcome the fears. You can stand in the shallow end so you feel safe and try putting your head underwater in various ways. Be gentle with yourself and take little steps until you start to feel comfortable with the water.</p>
                                <p>I also tend to exhale continuously while my face is under the water. (I blow water out my nose and imagine that those bubbles are propelling me through the water. This is obviously lunacy, but I still like the idea. It also keeps water out of my nose.) My goal is to not have anything left to expel when I rotate my head to breathe. I don't have a lot of time to breathe, so if I start out with a full breath, there'll be this choppy out-in that really won't make for a complete recycling of the air. When you do breathe in, focus on how you breath.</p>
                                <p>The issue here is getting enough oxygen. And one way you can improve your oxygen intake is by getting a full breath. I've spent years being aware of how to breathe properly (both with the Feldenkrais work, and in my life as a singer). And yet in the pool there was some sort of primitive anxiousness that meant I was only thinking about expanding my chest. Focus on breathing down into your belly (use your diaphragm) and I think you'll find yourself getting a more complete breath with more oxygen.    </p>
                                <p>Take the time to learn to breathe on both sides. It is such a help when you're racing to be able to look to either side and see the people around you. It means if the waves are hitting you on one side, you can choose to breathe on the other side. If the sun is bothering you on one side, breathe on the other. It gives you options you won't have otherwise. Most of the time when I'm doing my laps, I breathe every third stroke. This effectively alternates which side I breathe on and gives me equal practice breathing on both sides. I do remember in the beginning having a favorite side to breathe on. I was just better at it to one side. The tendency then, is to use the side that works best. But that way you'll never improve the side that's weak. Not what you want. So I do recommend three stroke breathing. But also be aware that breathing every third stroke doesn't cycle as much oxygen as breathing every other stroke. So when I'm racing and need the  extra oxygen, I go ahead and breath every other stroke. The good part is, now I've got complete freedom as to which side to use. The drawback when I'm breathing only on one side in a race is that my stroke becomes less than even between the two sides and I can start pulling to one side or the other. It's subtle but over time it adds up. So lately I've been playing around with alternating. I breathe a couple of times on one side, switch sides&nbsp;and then breathe a couple times there. Etc. But I also find that if I manage a full breath as discussed above, getting enough oxygen becomes less of a&nbsp;stumbling block.</p>
                                <p>Back to the issue of water in the mouth. When you breathe in the pool you don't have to turn your hard far to clear your mouth of the water. In fact there's a little eddy over near your shoulder where the water seems to recede to give you breathing room. That's where the pros do their breathing. And that always worked for me in the pool. However I've twice failed in open-water swims due to getting a mouthful of water. The last time I went on to barf twice. If you think vomiting while trying to tread water is fun, well, of course you don't. I'm just telling you it's not recommended. So lately I've been making a point of looking up toward the ceiling when I breathe. That gives my mouth some extra clearance. While I try to do the extra rotation with my head alone, you run the risk of over-rotating onto your side, which is not optimal swimming, but I just can't risk another mouthful of lake water. I don't handle it well. If you end up doing something similar, try and avoid&nbsp;looking up at the sky when you do&nbsp;it. There is no useful information up there. Swivel your eyes in the direction opposite to how your head is turning so you can keep track of your surroundings.</p>
                                <h3>Kicking</h3>
                                <p>So what about your feet? Well, the feet can help propel you forward. Unfortunately, they don't make for a smooth propulsion system. A huge part of the energy expended by fluttering your feet gets lost to all the turbulence you're creating with them. If you're trying to break the pool record, efficiency be damned. You better kick like all get out. The best swimmers in the world have powerful kicks. You're not competitive without one. If you get the chance, stop and watch a college swim team practicing. Those people can go as fast with their kick alone as I can with my full stroke. But for triathletes, Laughlin has an odd suggestion. Don't kick. Or at least kick very minimally. I kick once per stroke. If the right arm is entering the water, I give a little kick down with the left foot to help with the corkscrew rotation effect. And vice versa when the left arm enters the water, I kick down with the right foot. (If this confuses you, try thinking of it as <em>whichever side is pulling back, that's the side which kicks</em>.) But otherwise let your arms and your core muscles do most of the work. You're legs will have to peddle and run for miles when you get out of the water. Let them start the bike leg feeling something other than exhaustion. The kick I do is modest, a flick. Timing is everything. It needs to coordinate precisely with everything else. I will sometimes kick both feet for a second, intentionally breaking the surface to make sure the feet aren't dragging low behind me. It's a way of checking my horizontal flatness. But normally on the kick I don't want to break the surface. It's all done just below the surface. When you get done with your swim and making your way out of the water your legs can feel a little unsteady. Make a point of kicking in the last few minutes of the swim and you'll get the blood flowing to your legs in time for your exit. I will admit that I've been playing around lately with having a more ongoing kick. One thing to keep in mind, your kick helps you stay flat in the water. So any time I'm worried that my feet are starting to sink, I'll throw in some kicking to get myself properly horizontal.</p>
                                <p>People talk about moving through a horizontal pipe in the water. It's not really there. There's no pipe. But they think about keeping themself flat enough and streamlined enough to fit through an imagined pipe. They really don't want anything sticking outside the pipe and creating drag against the water. That means your legs, as they're kicking have to stay inside the pipe. If you have a big kick that moves outside the pipe, you might in some way get a little more propulsion out of it, but most of the gain will be negated by the extra drag you create. Try for a smaller flutter with your kicking rather than big giant kicks.</p>
                                <p>One last point about feet. A pointed foot will provide much less pushback against the water than a foot bent at a ninety-degree angle. If you're foot doesn't naturally stretch that way, well, I don't know. Good luck. If you're not shooting for the Olympics this may be a limitation you choose to live with.</p>
                                <h3>It's A Skill You're Learning</h3>
                                <p>Laughlin has another odd suggestion for triathletes: Don't push for endurance when you swim, work on your skill. In the pool you're a student of swimming. The endurance will happen as a natural by-product of being in the water and putting in the yards. And heck, your running and biking will get you in shape. Don't focus on that in the water. So most sessions I still stop every so often to catch my breath. I want every lap I do to be pleasant and done well. That happens best when I'm not struggling and tired. I'm trying to imprint quality swimming into my nervous system. As Moshe Feldenkrais once said, "Practice doing something poorly, and you'll get very good at doing it poorly." The point isn't to mindlessly put in the miles, but to practice swimming well. Of course, at some point you'll have to start lengthening your intervals. At some point you've got to teach yourself to swim the race distance you're up against without stopping. But if you let those sessions descend into incompetent struggle, how much good are you doing? So most sessions I take my twenty seconds of serenity between intervals, all the while thinking about what I'm going to work on for the next lap. Where should my focus go? Trying to remember all the points I've talked about is crazy-making. So I pick something to work on. Just one thing:<br></br>
                                    <br></br>
      * Keep your head down.<br></br>
      * How quietly can I sneak my hand into the water?<br></br>
      * Make good rotational kicks. Time them so they help propel you onto the other side.<br></br>
      * When rotating the head to breath, keep it low in the water. Don't lift the head. Chin toward your shoulder. There's a little cavity in the water there where you can breathe.<br></br>
      * Reach forward with your forward hand, extend.<br></br>
* Is the forward hand relaxed with the fingers hanging down, ready to pull back?<br></br>
                                        * Feel the corkscrew.<br></br>
                                            * Elbow out on the catch. Pull with the whole arm. When you do the catch really well you'll feel yourself surge through the water.<br></br>
                                                * Breath out while your face is underwater. You don't want your lungs full when the moment comes to grab a breath.<br></br>
                                                    * Brush the thigh with the thumb as you finish the catch. You can even add a little push backwards when the hand reaches your thigh.<br></br>
                                                        * On the recovery, when the arm is out of the water and coming forward, the elbow is high and the arm relaxed. The fingers less than an inch above the water. If you want to find out where your arm is positioned, try dragging your fingertips across the water. You don't want to do this permanently. It's just a drill to give yourself some feedback as to your arm position.<br></br>
                                                            * Make sure I don't start my hand pull (the catch) until the hand entering the water is ready to take the forward hand's place. Maybe I'll exaggerate that and have the hands touch before the pull back.<br></br>
                                                                * When I breathe, glide on my side for a second. Work on my balance.</p>
                                <p>These last two ideas are not how I'm really going to swim, but drills to help me learn. Because the whole thing is complicated. And it's hard to just decide to do everything right all at once. It helps to break things down into manageable sub skills. (Reminds me of the way Moshe Feldenkrais talked about chunking learning into manageable pieces.) And the man who's made a living out of that for swimming is Terry Laughlin. He markets what he does under the moniker of Total Immersion. There's a web site with DVDs and books and training guidance. Check it out at <a href="http://www.totalimmersion.net/" target="_blank" rel="noopener noreferrer">TotalImmersion.net</a>. If you're frightened of the water, they have a DVD called Happy Laps which shows you some drills you can try. If you're comfortable in the water and simply want to swim better, they offer a DVD-Book combination called <em>Easy Freestyle DVD</em>/ <em>Triathlon Swimming Made Easy</em> Book Bundle. Then there's the latest offering: <em>Total Immersion Self-Coached Workshop: Perpetual Motion Freestyle in 10 Lessons</em> which I suspect is meant to supplant <em>Easy Freestyle</em>. There's all sorts of stuff you might want to check out.</p>
                                <p>When I'm in the pool, one thing I keep coming back to is counting my strokes. How many strokes does it take to swim the length of the pool? If you're up in the mid twenties, you've got a clear indication that your stoke is not what it needs to be. The very best swimmers with a strong kick and perfect form can get down into the low teens. I've never gone below  15 strokes, and that's with a very strong push-off from the side of the pool and a lot of coasting. Notice that a strong push-off and lots of coasting have nothing to do with swimming well. In fact, if I've got a strong kick, I could do the entire length of the pool without a single stroke. My point being you can artificially alter your stroke count without improving your stroke. You don't want to  distort your stroke in order to get your count down. So use stroke count as a means of judging the quality of what you're doing, not an artificial goal. I suspect 19 or 20 strokes means you're doing most things right. If you're above that, start looking for ways to offer less resistance to the water.</p>
                                <p>One last point, if you're wearing baggy swim shorts, don't. That's like wearing an anchor as you swim. Burn them. Get something form fitting. I've got a pair of jammers that I wear when I don't want to embarrass the girlfriend. But for just putting in the laps, I've got one of those speedos they make jokes about. (Many male swimmers use a square leg training suit that's not so skimpy.) You'll obviously need goggles. Oh, and the swim toys. Put them in the closet for a while. Practice swimming.</p>
                                <p>Based on a lot of reading, I get the impression that there are some swim coaches who don't teach swimming. They hand out assignments about how many laps their students are supposed to swim. They just take it as a fact that some kids are naturally faster than others. But the best coaches believe that swimming well is a teachable skill. And they get to work teaching it.</p>
                                <p>All I know is it has worked for me. My swimming these days is actually fun. I can  slip through the water and get moving pretty fast without a lot of effort. I actually look forward to the workouts.</p>
                                <h4>The High Cadence Approach</h4>
                                <p>Some coaches recommend a high cadence in the water. That means increasing the number of times you stroke per minute. They believe you're more stable and less likely to get buffeted by your neighbors. They do this by dropping the moment spent gliding with arm outstretched. Instead they insert the arm deeper into the water (at least 15 inches below the surface at extension) and immediately begin the catch. This actually is ideal for drafting someone. First, you avoid bumping the persons toes. And second, that water where the kicking is happening is all frothy and not great for pulling against. The water below there is going to give you better purchase. But the faster turnover does require a high degree of endurance.</p>
                                <h3>Hair</h3>
                                <p>After I'd bumped up my swim training to nearly every day, the girlfriend sighed and said, "You used to have really nice hair." The chlorine in the pool can quickly turn your hair to straw. But there are things you can do. It really helps to get your hair wet before you get in the pool. You should shower any time you're getting in the pool; just make sure you soak your hair. That way the chlorine water from the pool isn't sucked into the dry hair. And a swim cap will make a huge difference in keeping the pool water away from your hair. Finally, there are shampoos that claim to help alleviate the effects of chlorine. </p>
                                <h3>Creating Endurance</h3>
                                <p>Sooner or later you'll have to work on your endurance. The sooner the better, actually. Except it's just such a bad idea to struggle through sloppy laps done poorly. So here's my suggestion. Go as long as you can without loosing your form. Don't put in miles of laps and end up rehearsing a bad stroke until it's imbedded into your nervous system. But if you can push it up to 100 yards and keep good form, put the 50 yard intervals behind you. If doing 400 yards without rest means you did the last 100 yards really sloppy because you were tired, then limit yourself to 300 yard intervals.  Your goal is to extend the distance you can swim <em>well </em>before needing to rest. Eventually you want is to be able to feel fatigue, and yet still swim well. See if you can retain good form when you're tired. But if the form falls apart, stop and recover.</p>
                                <h3>Making Progress</h3>
                                <p>This focus on form means you run the risk of going too easy on yourself. Don't be surprised if, in the beginning, 500 yards a session feels like a mountain to climb. I remember my back hurting and my goggles a complete bother. I think I spent more time clinging to the side of the pool and gasping for breath than I did swimming. But it does get better. Suddenly I was able to do 1000 yards. Then 1500. I think I plateaued there for a while. Trouble is, if you're taking 50 minutes to do 1500 yards because a third of the time is spent recovering, and you can only make it over to the pool a few times a week, then you've limited how much progress you can make. 4500 yards a week isn't quite cutting it. I got out of my rut by  focusing on swimming for a month. When you feel yourself stuck, you might want to try it. Go five times a week for a while. That will allow you to make some real progress. Next thing you know you'll be able to do 2000 yards in less than an hour. You can then fall back to three workouts a week for a month. Yet you'll now be doing 6000 yards a week. When you feel ready to take the next step maybe you focus on the swim again. After a few weeks of that you bump the distance again. You get the idea. If you can get to the point where you can swim continuously, suddenly your hour at the pool is adding up to maybe 2500 yards. You've just become so much more efficient with your time. And if you can do 2500 yards a pop, three times a week works. At least for a beginner.</p>
                                <p>I think before you attempt any race you're going to want to prove to yourself you can swim that distance without stopping. But don't just slog through it. Keep your focus on your form. If you're going for the Olympic distance tri,  twelve or fifteen thousand yards a week isn't a bad number to shoot for. Seem like a lot? It's all relative. Would you believe I've heard of serious swimmers in rigorous programs doing as much as 10,000 yards twice a day? In preparation for the Ironman next year, I've got myself up to 15,000 yards a week and I'm hoping I can go higher soon.</p>
                                <p>Once you feel like you've got your stroke in good shape, you have to build up your endurance. Have a distance you do each session that is well beyond what you're facing in the next race. Then time yourself. Can you do the whole distance without stopping? At first perhaps you won't be able to. But keep track of your time and keep trying to lower it. (Make a point of sighting at least once each lap, because that's part of what you'll have to do in open water.) Eventually you'll be able to keep going the whole way and you'll have cut gobs of time off your practice session. Which makes for a good moment when you should consider upping your distance.</p>
                                <p>There will be moments in the water when you want to be able to speed up. You need to be powerful in the water. Not just getting by. Every time you're at the pool, I would encourage you to do a few laps at full tilt. It's actually quite fun. But again, don't let your form slip. While I warn against too much intensity too soon when running, swimming is easy on your body. Throwing in some intensity is good for you. Make it a habit.</p>
                                <p>In the final analysis, what you want from your stroke is power. You want each stroke to provide as much forward momentum as humanly possible. This depends on&nbsp;a streamlined body and a good catch. A good catch means you don't let the water slip around the hand and arm just because it's easier that way. Imagine your hand is stuck in concrete and can't move through the water, but your body can move over the hand. I'd rather see you do this slowly than do it quick and sloppy. Once you've got a great catch, you can speed things up. But at the end of the season, when I'm no longer feeling pressured about ramping up for a specific distance, this is where my focus returns.</p>
                                <p>Open-water swimming is a whole other issue. <a href='/Triathlon/TriOpenWater.html'>There's a separate page on that.</a></p>
                            </div>
                        </Col>
                    </Row>
                </Col>
            </Row>

        </Container>
    )
}