import React from 'react'
import { Container, Row, Col } from 'react-bootstrap'

import FeldenkraisIndex from './FeldenkraisIndex'
import FeldenkraisTitle from './FeldenkraisTitle'

export default function UserQuotes() {

    return (
        <Container>
            <Row>
                <FeldenkraisIndex />
                <Col>
                    <FeldenkraisTitle />
                    <div className='text-center'>
                        <h1>User Quotes for</h1>
                        <h3>The Feldenkrais Lessons: Awareness Through Movement</h3>
                    </div>
                    <p><span class='quote'>"I've just finished working my way through all 48 lessons on your CD. Brilliant! Really great teaching and the clarity of explanation of a physical movement is so impressive. I recommend you whenever there's an opportunity. Thanks"</span>
                        <br></br>Dr. Matthew Selman, Clinical Psychologist, Newcastle, United Kingdom <br></br><br></br>
                        <span class='quote'>"I've been doing your tapes almost daily since Feb. and all I can say is a thousand thank-yous. I really, at age 53, have a brand new body! It has been just what I needed so badly and had been searching for. I had been getting so stiff and tired and sore, even with exercise, and healthy eating, etc. I knew I didn't move right, but didn't know how to change.
                        And now every moment is a joy. It is fluid and graceful and effortless to go through daily life. Some of the specific changes are: my back- it always bothered me about 2/3 up, a lot of pain and tension. Chiropractors helped, but it never lasted. It was always sore to the touch and a couple of vertebrae stuck out. Now it is completely strong and comfortable, no matter what I do, and feels so good! A miracle. All my life my knees have cracked whenever i squatted down- now very rarely. I had a chronically sore shoulder-now almost perfect. I had a large callous on the ball of one foot that was really starting to bother me-it's almost gone.
                    I feel so flexible and limber now. Sometimes in the middle of a tape I feel such a wave of gratitude to Dr. Feldenkrais and his genius, and for what he has given me and the thousands of others he has helped. Thanks so much for your tapes and part in all this help!"</span>
                        <br></br>Edith Spencer, Greenwich, Connecticut <br></br><br></br>
                        <span class='quote'>"I can't tell you how much I've enjoyed and benefitted from the Feldenkrais tapes. You did a beautiful job on them. I have done the whole set twice now, in the less than a month since I've gotten them, and the more I do the deeper my appreciation for Moshe, for you, for life. I did yoga for fifteen years, and taught it for ten. I am trained in a variety of approaches to body therapy including creative movement, sacred dance, bio-energetics, Lomi Body-Work, and polarity, and I have had a private practice in psychophysical therapy for ten years. I mention all that to give weight to my feeling that your tapes are fantastic, wonderful, superb, magnificent, and fun."</span>
                        <br></br>John Robbins, Victoria, Canada <br></br><br></br>
                        <span class='quote'>"This is the first exercise program of many that I've attempted that I stick with, and even look forward to. I think this is due to the variety involved day-to-day, the pleasurable feelings of doing them, and how good I feel afterwards emotionally."</span>
                        <br></br>Wendy MacDonald, British Columbia <br></br><br></br>
                        <span class='quote'>"They have gradually worked out pain and stiffness I have had for at least ten years. I am 66 years old-and after working through your tapes six times I feel 66 years young."</span>
                        <br></br>Emma Nagel, Dallas, Texas <br></br><br></br>
                        <span class='quote'>"Bought your CD months ago. Things got busy. Only did a handful of lessons. Liked them so much, signed up for a 3 hr workshop in NYC. Was so disappointed, your lessons were actually much better and easier to follow. Thank you for this most valuable resource."</span>
                        <br></br>Noreen Hernandez, Highland Lakes, New Jersey <br></br><br></br>
                        <span class='quote'>"I think that the entire set is terrific! I have been devoting an hour a day to the exercises for the last five or six months and the results are fantastic. I had a problem with numbness in the toes and ball of my right foot that had been getting progressively worse over a period of years (it started when I was about 53 years old and I am 63 now). The results seem to be that I am getting the feeling back in the toes and ball of the foot gradually. The toes on both feet are gradually spreading more and more. My posture has improved substantially-chest lifted, head on straighter, stomach tighter-and I get a kick out of people constantly telling me how young I look.
                    I certainly appreciate your producing the tapes. They are extremely well done: good timing, excellent voice, and a nice quiet relaxed quality that includes a little humor. I really enjoy listening to them, no matter how many times I hear them. You have done a great service for the Feldenkrais movement! If you ever need an endorsement for any purpose , let me know."</span>
                        <br></br>Frank Pieper, Minneapolis, MN <br></br><br></br>
                        <span class='quote'>"I would like to write and add my words of praise for the gifts you have given through your tapes. I am an exercise physiologist and have worked several years with traditional and non-traditional exercise methods as a teacher and student. Your tapes added a dimension I did not know was there. I will be forever grateful for the value I have gained as an exerciser and as a teacher. Specifically, I've opened up new worlds for my running through increased pelvic motion. Also, my dancing has improved 100%! I've been able to pass much of this knowledge on to my students and open up new possibilities for them to move and exercise in a more relaxed confident manner. Techincally, Bruce, I also congratulate you. The tapes are very clear and easy to follow for everyone, professional to beginner. They are also pleasent to listen to, I will definitely recommend them to my student and fellow professionals."</span>
                        <br></br>George Hetzel, Coronado, California <br></br><br></br>
                        <span class='quote'>"Your tapes have meant so much to me, I decided I wanted to write to you. I am now walking in a completely different manner. In the past, I was always afraid I might trip and fall; now, when I walk or move, I feel as though I'm floating.
                        This is such a precious gift for someone who has always thought of herself as awkward. I feel more graceful than I ever believed I could, and this has helped me relate to my world in a much more positive way.
                    The tapes are clear, well put together, and best of all, non-judgemental and encouraging in tone. I'm very glad I own them. Thank you."</span>
                        <br></br>G.A., Evanston, Illinois <br></br> <br></br>
                        <span class='quote'>"I can't thank you enough for putting the audio tapes of your Feldenkrais classes on a CD!
                        I was a wrestler at Oregon State University, I graduated this spring. For about three years of my time wrestling in college I had extreme pain in my hips, knees, back, and neck. Wrestling had always been my passion, but it became impossible to enjoy, and actually depressed me with how incapable I was of reaching my full potential. I got to a point where I was incapable of walking without a bad limp.
                        Nearly defeated going into my senior year, I considered quitting wrestling because I couldn't handle putting my body through the abuse of daily wrestling practice. Instead, I simply changed my thinking and desperately searched the internet for something that could give me any relief. Because believe me, I had tried every form of physical therapy I was aware of. Then, I somehow stumbled across Moshe Fedenkrais and the method he developed. I knew it was exactly what I needed! I had terrible movement patterns. I had most likely always moved inefficiently, but it had worsened over the many injuries I incurred throughout my wrestling career, and finding ways for my body to compensate while still wresting. I looked at a lot of Feldenkrais instructor reviews before I chose to order your CD, and I couldn't be happier that I picked yours!
                        I must have finished the whole CD my first time through in less than a week! I went from hardly being able to walk, being so frustrated, and down right depressed. To having a complete breakthrough in my wrestling and overall body movement. I could have easily quit wrestling and never known what could have been, but I ended up becoming a Pac-12 champion this year, and finished top 12 in the country at the National tournament. It's all thanks to you Bruce!
                        My only regret is not discovering the Feldenkrais method, and you, sooner! I know I could have been a National Champion. I still have so much recovery to make with my body before I feel I am moving at my best. But before I found your CD's the image I had of myself at age 40 was a decrepit broken old man, because I had no idea how to fix my dysfunction. Now I've rid myself of pain almost entirely and have such a bright outlook because I no longer have pain doing basic every day tasks.
                        I just felt like I needed to let you know how much I appreciate your knowledge as a Feldenkrais instructor. I feel like I know you in a way, I have some of my favorite lessons nearly memorized from how many times I've heard you speak them!
                    You're awesome Bruce! Although we've never met, I appreciate all you have done for me!  Sincerely your fan,</span>
                        <br></br>Alex Elder, Salem, Oregon <br></br><br></br>
                        <span class='quote'>"To this day it is hard for me to believe that two concentrated days with you in the Feldenkrais Workshop stopped back pain that three years of medicine could not stop. I do not ever remember being so relaxed and comfortable as I was at the end of the second workshop day. What has amazed me the most, however, was that I continued to feel relaxed and have continued on the most part without any pain! I have enjoyed and benefitted from the use of the tapes."</span>
                        <br></br>Ginger Cook, Houston, Texas <br></br>
                        <span class='quote'>"Incorporating Feldenkrais with yoga has increased my flexibility and improved my yoga postures. As I get more and more addicted to the Feldenkrais method, I find my yoga classes (and me!) changing greatly, with accelerated improvement for all of us. You did a wonderful job on the cassettes. Thank you."</span>
                        <br></br>Ruth Hetzel, Evansville, Indiana <br></br><br></br>
                        <span class='quote'>"...Many of the cassettes help my eyes. When I had my detached retina operation the eye refuse to manufacture fluid. It has slowly resumed function but many of the gentle head movements actually cause my eyes to relax and become more fluid... I'm sure I'm a Feldenkrais student for life."</span>
                        <br></br>Judy Lipke, Lombard, Illinois <br></br><br></br>
                        <span class='quote'>"I've been really amazed by how good (balanced, comfortable) my body has felt after doing even a single side of your tapes. When I was listening almost daily I felt good all the time. Now, whenever I feel the need I listen to one of the tapes and whatever stress or back pain I've been experiencing as a result of a limb length discrepancy and scoliosis leaves me. My body feels organized in a new way it doesn't as a result of the other things I've tried-dance, Tai Chi, yoga. As a result, I've recommended the tapes to several friends and consider them a godsend."</span>
                        <br></br>E.J., Chicago, Illinois <br></br><br></br>
                        <span class='quote'>"For anyone hoping to understand and use Feldenkrais's work, the tapes are a tremendous advanage. The material is concise, orderly, and represents the most effective method of learning the gentlest and most profound of movement therapies."</span>
                        <br></br>Barrett L. Dorko, LPT, Cuyahoga Falls, Ohio. Ohio Falls Orthopaedic Surgeons <br></br><br></br>
                        <span class='quote'>"...they've shown me how to relax and ever since I've noticed that I never have pain in my lower back..."</span>
                        <br></br>P.B. Ottawa, Ontario <br></br><br></br>
                        <span class='quote'>"...I'm able to define definite changed in my stature, my head stands taller, my back and neck straighter, and my shoulders aren't hunched up towards my head."</span>
                        <br></br>G.K., Kalamazoo, Michigan <br></br><br></br>
                        <span class='quote'>"Have been using your cassettes of Feldenkrais Awareness Through Movement exerices and am writing you to tell you how excellent they are.
                    Several years ago I attended a weekend workshop taught by Moshe Feldenkrais. Within two weeks of that experience I lost 30 lbs. of weight and a further 20 lbs. within 3 months. Although I had to purchase a complete new wardrobe to fit my body, the feeling of well-being and the change in my self image more than compensated for the cost. Your cassettes present the exercises most clearly and are easy to follow."</span>
                        <br></br>R.M., Vancouver, British Columbia <br></br><br></br>
                        <span class='quote'>"I had the funniest experience the other day. I had my physical with the same doctor I have it with every year, and he could not believe it. I am 1/2 an inch taller than before. He kept measuring me, looked at the chart from last year and the year before and finally asked what I am doing lately (he knew I teach yoga). So I told him that I am doing Feldenkrais exercises. He could not believe that the spine can stretch out if the muscles are relaxed, but I proved it. Normally they tell you that you are shrinking with age, now at 72 I am growing. Ha! My times in swimming in the Senior Olympics went up too, my jogging feels even easier than ever, through the Hamstring and Hipjoint exercises the stride gets longer. Bruce, you are just beautiful having done this fantastic job with the cassettes!"</span>
                        <br></br>Ruth Bender, Avon, Connecticut <br></br><br></br>
                        <span class='quote'>"I have been using your cassettes and find they help me tremendously in my work as an actress. My work has become much more calm and truthful. The Feldenkrais method is very valuable to performers."</span>
                        <br></br>Marilyn Kay Caskey, New York, New York <br></br><br></br>
                        <span class='quote'>"My bursitis-which I have had for two years in my left shoulder is mostly gone-apparently due to doing these exercises. I find the relaxed quality of your voice, with the clarity of directions you give as part of the effectiveness which leaves me feeling more clear headed & in control of my body..."</span>
                        <br></br>B.J., Denver, Colorado <br></br><br></br>
                        <span class='quote'>I have been thinking about trying to contact you for several years to tell you how much your Feldenkrais lessons have meant to me over the years and finally decided to do it. While I was browsing your web site, I read what you said about not winning first prize with your music. While your music may not be winning first place, your Feldenkrais lessons are first place with me. I can speak with authority because I have about 18 other sets of Feldenkrais lessons by numerous well known teachers. Yours are hands down the best. I like all of the other Feldenkrais material I have very much, but you are much more personable, engaging, and thorough than any of the other teachers.
                        Wow, what a value. Your work is the single most effective self help I have found in 40 years. That includes many thousands of dollars worth of tapes, CD's, books and workshops covering everything, and I can add psychotherapy to that. That is the best value anybody will ever find for self help.
                        It has been very comforting to have you with me on my journey. I started doing the exercises again a while ago and just finished #38. I feel and learn something new every time I do them. Thank you for being there.
                    All the best to you. Very Kind Regards,</span>
                        <br></br>Bill Jackson <br></br><br></br>
                        <span class='quote'>Thanks so much, my CD (plus the bonus music one :) arrived safely a few weeks ago. I am not as diligent as I'd like to be, but I am REALLY enjoying the process! I am astounded at how differently I walk, how differently I carry myself after each session! Thank you for offering this amazing program! Blessings,</span>
                        <br></br>Diane Korol <br></br><br></br>
                    </p>
                </Col>
            </Row >
        </Container >
    )
}